name: Update Greeting

on:
  schedule:
    - cron: "0 * * * *" # 每小时运行一次
  workflow_dispatch:

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: greghe/greeting-action@main
        with:
          # 文件路径，用于替换上面 README.md 中的占位符
          path: 'README.md'
          # 替换的开始和结束标记
          start: ''
          end: ''