name: Generate Snake Game

on:
  schedule:
    - cron: "0 0 * * *" # 每天午夜运行，自动更新
  workflow_dispatch: # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Platane/snk@v2
        with:
          # GitHub 用户名
          github_user_name: ${{ github.repository_owner }}
          # 输出文件路径
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
          # 动态效果设置
          commits_by_year: false
          
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output # 注意：这里的 output 对应 README.md 链接中的路径
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}